### PR TITLE
XLMOD: Updated version and fixed OBO errors

### PR DESCRIPTION
**Pull request by pmt706**
Issues:
1. The ID's in property_value cannot have whitespace, so I changed "base specificities" to the camel cased "baseSpecificities" and "secondary base specificities" to "secondaryBaseSpecificities".
2. There was also a couple of missing quotations.

I also generated the corresponding OWL file from this version. using ROBOT.

Before we roll these changes into OBOFoundry, I'd propose that we get it homed at a root within the HUPO-PSI organization.

### CODE REVIEW

**Comment by pmt706** [comment]
references #117 and subsumes and fixes #116 too

**Review by edeutsch — APPROVED** [review]
Thanks, looks good to me!

**Comment by pmt706** [comment]
Thanks! Who's the "arbiter of merges" for the mzIdentML repo?

**Comment by edeutsch** [comment]
I don't really know, but this is just fixes that don't seem like they could be potentially controversial, so I will try to merge.

**Pull request merged**
