### PR TITLE
[FIX] fixed validation issues with QXQ files, updated examples, added…

### PR DESCRIPTION
**Pull request by mwalzer**
… scores

### CODE REVIEW

**Comment by mwalzer** [comment]
fixes https://github.com/HUPO-PSI/mzIdentML/issues/52

**Comment by mwalzer** [comment]
https://github.com/HUPO-PSI/mzIdentML/issues/57

**Comment by edeutsch** [comment]
Sorry, I don't understand enough about git to know what to do with a pull request. How do I apply your pull request (PR#66?) to my local copy of the repo without it being in the master?

**Comment by mwalzer** [comment]
Yes, no problem. I had commented direct links to the updated files in the [respective issues comment section](https://github.com/HUPO-PSI/mzIdentML/issues/52#issuecomment-230726074).
But I will go on and merge, then you would only have to update.
Regarding your question, I created a little wiki entry about git usage. Probing the entire pull request branch would require a complete checkout of my pull request branch. Or inspection of the changed files via interface or direct (download) access through github.

**Pull request merged**
