### PR TITLE
Fix error that occurs during cs class generation

### PR DESCRIPTION
**Pull request by stefanks**
This error and solution:
http://stackoverflow.com/questions/6678934/unable-to-generate-a-temporary-class-result-1-error-cs0030-cannot-convert-ty
https://developer.salesforce.com/forums/?id=906F0000000AiPEIA0
http://stackoverflow.com/questions/5595779/xmlserializer-invalidoperationexc-known-issue-converting-types

### CODE REVIEW

**Comment by andrewrobertjones** [comment]
Hi @stefanks can you give me the plain English description of the issue and solution? Thanks Andy

**Comment by stefanks** [comment]
I'm trying to automatically generate a usable class to use in C# on windows. Usually it works by running the command xsd.exe theSchema.xsd /classes in the visual studio developer console. Because of a bug in xsd.exe, it generates a class with a double array instead of a single array anytime it encounters maxOccurs="unbounded" in the xsd schema. 

Since microsoft has not fixed the error, adding this harmless line streamlines the workflow for anyone trying to automatically generate a class from the schema. 

Does it break any use/test cases?

**Comment by andrewrobertjones** [comment]
It appears that you would like to add an attribute "tmp" to one of the elements, to fix a downstream bug in a piece of Microsoft software? The addition of the attribute wouldn't be harmless, since people could put data in the attribute - or do I misunderstand? We wouldn't normally change the standard to fix downstream bugs in software

**Comment by stefanks** [comment]
Yeah, I agree that it's not a good idea to change the schema to fix downstream bugs. I just wish standard tools were working without any hacks...

**Pull request closed without merging**
